# Site settings
title: "The Shadow AI"
email: infinixsmartplus01@gmail.com
description: >-
  Synthesizing AI signals into digital philosophy.
  An elite perspective on the autonomous future.
baseurl: "/ShadowAI"
url: "https://Baluch2.github.io"
