# Site settings
title: "The Shadow AI"
email: infinixsmartplus01@gmail.com
description: >- 
  Synthesizing AI signals into digital philosophy. 
  An elite perspective on the autonomous future.
baseurl: "" # Keep empty if your site is at username.github.io/ShadowAI
url: "https://Baluch2.github.io/ShadowAI" 

# Build settings
theme: minima # Or "remote_theme: mmistakes/minimal-mistakes" for a pro look
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permissions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  remote_theme: cotes2020/jekyll-theme-chirpy
